data "aws_region" "current" {
  lifecycle {
    postcondition {
      condition     = contains(local.supported_regions, self.name)
      error_message = "Region must be one of: us-east-1, us-east-2, us-west-2. Contact support if you need a new region to be supported."
    }
  }
}

locals {
  # Lambdas can only be deployed from s3 buckets in the same region. These are
  # the regions where we currently host our lambda code
  supported_regions = ["us-east-1", "us-east-2", "us-west-2"]
  lambda_s3_bucket  = "braintrust-assets-${data.aws_region.current.name}"
  # This file is generated by the release process and contains the path to the
  # latest lambda versions for each lambda function
  lambda_versions = jsondecode(file("${path.module}/VERSIONS.json"))

  postgres_url = "postgres://${var.postgres_username}:${var.postgres_password}@${var.postgres_host}/postgres"

}
